### ISSUE TITLE
关于melodic(Ubuntu 18.04)的使用

### ISSUE THREAD

**Issue by pipixia-wei** [6-robot/wpr_simulation#1]
请问这个可以在Ubuntu 18.04上面实现吗？

**Comment by zhangwanjie** [comment]
应该可以的，请先执行下面的指令确保所有组件安装完整：
`sudo apt-get install ros-melodic-desktop-full`

**Comment by pipixia-wei** [comment]
> 应该可以的，请先执行下面的指令确保所有组件安装完整：
> `sudo apt-get install ros-melodic-desktop-full`

谢谢您的解答！
但是我遇到了一个问题，就是在gazebo中无法显示床、桌子等东西，能够看到的只有四面的墙，请问您知道这是什么原因吗？（ubuntu18.04环境下）

**Comment by zhangwanjie** [comment]
看看终端窗口里提示了什么出错信息，可否截图贴一下？

发自我的iPhone

**Comment by pipixia-wei** [comment]
谢谢回复！我主要遇到了以下问题：

1.在工作空间执行catkin_make操作时，有以下信息的提示：
2.在运行wpb_gmapping.launch时有以下提示信息，但这个我在网上查阅资料，似乎是因为没有连接手柄（我后期是使用键盘进行控制的）：
3.在gazebo中显示如下，只有四周的墙：


4.在使用ctrl+c进行退出时，会有以下提示：


以上就是我的所有截图，因为刚接触ros，很多问题不知道怎么回事，非常感谢您的耐心解答！








在 2020-05-19 09:11:22，"Jay Zhang" <notifications@github.com> 写道：

看看终端窗口里提示了什么出错信息，可否截图贴一下？

发自我的iPhone

**Comment by zhangwanjie** [comment]
![2020-05-19 20-38-53屏幕截图](https://user-images.githubusercontent.com/17635413/82327314-ca281480-9a10-11ea-88d4-bc3a94568dda.png)
截图好像显示不出来……

**Comment by pipixia-wei** [comment]
> ![2020-05-19 20-38-53屏幕截图](https://user-images.githubusercontent.com/17635413/82327314-ca281480-9a10-11ea-88d4-bc3a94568dda.png)
> 截图好像显示不出来……

非常抱歉，不知道什么原因没有上传上去，问题与截图如下：

1.在工作空间执行catkin_make操作时，有以下信息的提示：
![catkin_make的提示信息](https://user-images.githubusercontent.com/55380789/82355188-762f2700-9a34-11ea-85f9-6166a1f7f23d.png)
2.在运行wpb_gmapping.launch时有以下提示信息，但这个我在网上查阅资料，似乎是因为没有连接手柄（我后期是使用键盘进行控制的）：
![运行wpb_gmapping launch的提示信息](https://user-images.githubusercontent.com/55380789/82355285-96f77c80-9a34-11ea-8b2b-8b30ca2899eb.png)
3.在gazebo中显示如下，只有四周的墙：
![gazebo显示](https://user-images.githubusercontent.com/55380789/82355334-a5459880-9a34-11ea-8006-1b989a58f0f5.png)
4.在使用ctrl+c进行退出时，会有以下提示：
![ctrl+c退出的提示信息](https://user-images.githubusercontent.com/55380789/82355376-b4c4e180-9a34-11ea-9184-13002cb2c572.png)

以上就是我的所有截图，感谢您的耐心解答！

**Comment by zhangwanjie** [comment]
谢谢反馈问题，貌似是规划器里的一个类文件没编译进去，我再查一查是什么问题。

**Comment by pipixia-wei** [comment]
> 谢谢反馈问题，貌似是规划器里的一个类文件没编译进去，我再查一查是什么问题。

好的，非常感谢！

**Comment by zhangwanjie** [comment]
catkin_make编译的问题已经修复，麻烦clone一下wpb_home的新代码。房间里没有加载家具的问题还没复现出来，我再找找问题。

**Comment by pipixia-wei** [comment]
> catkin_make编译的问题已经修复，麻烦clone一下wpb_home的新代码。房间里没有加载家具的问题还没复现出来，我再找找问题。

好的，已经试过了，catkin_make的问题已经解决，谢谢啦！

**Comment by zhangwanjie** [comment]
房间里家具没加载的问题也已经修复，麻烦clone新代码再试一下：）

**Comment by pipixia-wei** [comment]
> 房间里家具没加载的问题也已经修复，麻烦clone新代码再试一下：）

试过之后已经没有问题，家具也可以正常显示了，slam建图与导航都没有问题，非常感谢您的帮助！
只是在我运行roslaunch wpr_simulation wpb_gmapping.launch的文件时出现以下提示，虽然最终能够正常导航，但是不知道这个会不会对最终结果造成影响呢？
![2020-05-22 18-00-45 的屏幕截图](https://user-images.githubusercontent.com/55380789/82657051-4744cb00-9c57-11ea-8205-20519b95eab4.png)
最后再次感谢您的耐心解答。

**Comment by zhangwanjie** [comment]
这个提示加载cupboard小橱柜出错，但是实际已经加载成功了（目前场景里只有两个小橱柜，都在厨房那个房间里）。这个在性能不是特别好的电脑里会偶尔出现，而且每次还是不同的家具报错，在性能比较好的电脑上这个报错就不出现了，感觉应该是家具太多同时加载瞬时压力太大导致的。毕竟gazebo是个来源免费软件，不好苛求太多…
最后再次感谢你的反馈，让我们发现问题，谢谢~

发自我的iPhone

**Comment by pipixia-wei** [comment]
> 这个提示加载cupboard小橱柜出错，但是实际已经加载成功了（目前场景里只有两个小橱柜，都在厨房那个房间里）。这个在性能不是特别好的电脑里会偶尔出现，而且每次还是不同的家具报错，在性能比较好的电脑上这个报错就不出现了，感觉应该是家具太多同时加载瞬时压力太大导致的。毕竟gazebo是个来源免费软件，不好苛求太多… 最后再次感谢你的反馈，让我们发现问题，谢谢~ 发自我的iPhone
> […](#)
> 在 2020年5月22日，18:09，pipixia-wei ***@***.***> 写道： ﻿ 房间里家具没加载的问题也已经修复，麻烦clone新代码再试一下：） 试过之后已经没有问题，家具也可以正常显示了，slam建图与导航都没有问题，非常感谢您的帮助！ 只是在我运行roslaunch wpr_simulation wpb_gmapping.launch的文件时出现以下提示，虽然最终能够正常导航，但是不知道这个会不会对最终结果造成影响呢？ 最后再次感谢您的耐心解答。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，对结果没有影响就好，感谢您的解答。
因为我也是刚接触ros，遇到问题也尝试自己查阅资料解决，但网上总找不到正确的答案，非常感谢您的指导！

**Comment by zhangwanjie** [comment]
网上的ROS资料确实比较分散，而且ROS版本太多，难免各种问题，这也是我们做这个的意义，希望能帮助开发者快速入门和进阶。多交流：）

**Comment by pipixia-wei** [comment]
> 网上的ROS资料确实比较分散，而且ROS版本太多，难免各种问题，这也是我们做这个的意义，希望能帮助开发者快速入门和进阶。多交流：）

是的，你们这个对于初学者简直就是福利，能够让我很好地复现相关功能，之后在此基础去理解代码，从而实现快速入门。
总之，感谢你的帮助以及做的开源项目，日后有机会多多交流！
