### ISSUE TITLE
请问运行 roslaunch wpr1_controllers.launch 出现以下问题，打不开gazebo是怎么回事，所有的control依赖包都检查安装了，感谢！

### ISSUE THREAD

**Issue by lalala548** [6-robot/wpr_simulation#4]
[ WARN] [1621863358.241871717]: wpr1_joints_init
[WARN] [1621863378.677513]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[wpr1/controller_spawner-2] process has finished cleanly
log file: /home/lzc/.ros/log/f284cc50-bc94-11eb-acf0-e5f1d6280b7b/wpr1-controller_spawner-2*.log

**Comment by zhangwanjie** [comment]
你好，这个wpr1_controllers.launch一般不单独运行，它只是提供了一些虚拟的controller与ROS系统对接，它不会弹出gezebo。你可以试试其他的"wpr1_"开头的launch，它们都包含了wpr1_controllers.launch。

**Comment by lalala548** [comment]
那这个启明机器人有没有关于臂的控制仿真接口呢？

**Comment by zhangwanjie** [comment]
有的，你可以参考启明的实验指导书，然后再看这个仿真例程就比较清楚了。实物和仿真的接口是一样的。

**Comment by lalala548** [comment]
但是启明并没有安装moveit的功能接口是吗？

**Comment by lalala548** [comment]
但是启明并没有安装moveit的功能接口是吗？

**Comment by zhangwanjie** [comment]
> 但是启明并没有安装moveit的功能接口是吗？

六自由度机械臂版本的启明带有MoveIt接口，三自由度机械臂版本的启明没有接入MoveIt。因为三个自由度约束性太强，目标姿态稍微给得不合适就会出现无解情况，不如三角函数直接算来得直观:)
