### ISSUE TITLE
运行程序报以下错误，麻烦帮忙看下

### ISSUE THREAD

**Issue by diaokaitian** [6-robot/wpr_simulation#6]
![Uploading 微信截图_20210812225343.png…]()
[ERROR] [1628779188.296601720]: Map_server could not open /home/passoni/catkin_ws/src/wpr_simulation/maps/map.yaml.
process[robot_state_publisher-23]: started with pid [4387]
process[joint_state_publisher-24]: started with pid [4394]
[map_server-20] process has died [pid 4376, exit code 255, cmd /opt/ros/melodic/lib/map_server/map_server /home/passoni/catkin_ws/src/wpr_simulation/maps/map.yaml __name:=map_server __log:=/home/passoni/.ros/log/22f62fc6-fb7b-11eb-992b-000c298cff20/map_server-20.log].
log file: /home/passoni/.ros/log/22f62fc6-fb7b-11eb-992b-000c298cff20/map_server-20*.log
process[rviz-25]: started with pid [4399]
[ INFO] [1628779190.178677709]: Requesting the map...
[ WARN] [1628779190.241650328]: Request for map failed; trying again...
[ INFO] [1628779199.670291687]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1628779199.735752950]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1628779200.199552313]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1628779200.241250862]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1628779211.193386359]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ERROR] [1628779212.004623, 266.729000]: Spawn service failed. Exiting.
[ WARN] [1628779212.397909120, 266.730000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 266.73 timeout was 0.1.
[bookshelft-7] process has died [pid 4361, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -file /home/passoni/catkin_ws/src/wpr_simulation/models/bookshelft.model -x 2.0 -y -0.55 -z 0 -Y -1.57 -urdf -model bookshelft __name:=bookshelft __log:=/home/passoni/.ros/log/22f62fc6-fb7b-11eb-992b-000c298cff20/bookshelft-7.log].
log file: /home/passoni/.ros/log/22f62fc6-fb7b-11eb-992b-000c298cff20/bookshelft-7*.log
[tea_table-6] process has finished cleanly
log file: /home/passoni/.ros/log/22f62fc6-fb7b-11eb-992b-000c298cff20/tea_table-6*.log
[Err] [REST.cc:205] Error in REST request

**Comment by diaokaitian** [comment]
![微信截图_20210812225343](https://user-images.githubusercontent.com/22146168/129219178-9d4a8673-584a-4131-968f-8340bc1a1519.png)

**Comment by zhangwanjie** [comment]
从报错信息来看，是Map_server没有找到地图文件导致的问题。我猜想是没有经过SLAM建图直接运行导航launch是吧:)
可以搜一下微信公众号“六部工坊”，在历史文章里有这个系列的教程。先在SLAM那个实验里创建好环境地图，再用那个建好的地图进行导航，就不会出现这个问题了。

**Comment by diaokaitian** [comment]
好的，看到文章了，问题已解决，非常感谢
